---
title: "Prediction of New Onset Atrial Fibrillation Using Routinely Reported 12-Lead
  ECG Variables and Electronic Health Data"
author: "Alina Yildir, Archana Senthil, Harpreet Saini"
date: "2024-12-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Background

Atrial fibrillation (AF) is the most common heart rhythm disorder, currently recognized as the 21st-century cardiovascular disease epidemic, with an estimated lifetime risk of up to 1 in 3 individuals above the age of 45 years.1,2 Among the most serious complications of this disorder is developing blood clots in the heart that can dislodge and cause stroke, with a 4- to 5-fold increased risk in these patients.1,3 Accurate prediction of developing future AF is important for early initiation of anticoagulant medications to prevent such devastating complications. Several risk scores have been developed for the prediction of AF using traditional statistical models, such as the C2HEST4 and CHARGE-AF5 scores, with modest performance in validation datasets (C-index 0.59-0.73). Additionally, some of these scores have been derived for restricted ethnicity groups. Recently, machine learning (ML) algorithms have been explored for this task and have shown improved predictive performance. One such study incorporated patient-reported, electronic health record (EHR), and cardiac MRI-derived features, using a survival-based ML approach over a follow-up of five years, achieving a C-index of 0.78.6 Another ML model, FIND-AF, was derived in a UK primary care setting using routinely collected EHR variables for short term prediction of new-onset AF at 6 months, with an ROC-AUC of 0.82.7 There is an ongoing need to develop accurate AF prediction models that are generalizable to patients routinely encountered across all clinical practice environments.  Whether routinely reported ECG markers can improve prediction accuracy above conventional EHR variables is currently unknown.

# Research Question

Using a large repository of synthetic patient health data inclusive of 12 lead ECG and EHR variables captured from patients with suspected or known cardiovascular disease in Southern Alberta, can you develop a risk prediction model that can accurately predict the future occurrence of new-onset AF for individual patients?

**Study cohort:** A synthetic cohort of ~100,000 patients who have no prior history of AF and had a baseline ECG performed between January 2010 and January 2023, followed by a minimum follow-up of 12 months. Current or prior AF/flutter will be excluded on the basis of baseline ECG plus a review of prior continuous ambulatory ECG monitoring (Holter), ICD-10-CA codes, or procedural codes related to AF/flutter interventions. This synthetic dataset has been generated by training off a randomly identified subset of ~100,000 patients from the Cardiovascular Imaging Registry of Calgary (CIROC).

**Outcome of interest:** New-onset future AF/flutter detected by any follow-up ECG, continuous ambulatory ECG monitoring (Holter), ICD-10-CA code, or procedural code for AF/flutter intervention.

# Variables

Core demographics for each patient will be provided, including age and birth sex, followed by ICD-10-CCA/CCI-coded baseline comorbidities, cardiac history, and coding for which cardiac procedures each patient has undergone. Diagnostic testing variables will include routinely reported ECG variables and patient location at the time of baseline ECG (in-patient versus out-patient), followed by a collection of laboratory (blood) test variables captured surrounding the time of each ECG. Coding of all cardiac medications actively prescribed at the time of baseline ECG will also be provided.

See below a complete list of variables and definitions.

## System

### Tracking:

`patient_id` (alpha_num): Randomly generated 9-digit alpha-numeric identifier for each unique patient; first letter denotes source of identifer generration									

## Demographics

### Age:

`demographics_age_index_ecg` (numeric):	Chronological age at time of referenced index ECG, rounded down to nearest whole number

### Sex:

`demographics_birth_sex` (categorical): Sex assigned at birth (Male/Female)	

## Cardiac Risk

### Hypertension:

`hypertension_icd10` (boolean) ICD-10 coding of hypertension in either DAD or NACRS databases at any time prior to or 6 months after date of index 12 lead ECG (No/Yes)

### Diabetes:

`diabetes_combined` (boolean) Documented presence of hyperglycaemic state inclusive of Type 1 diabetes, Type 2 diabetes, Pre-diabetes, or Impaired fasting glucose (treated or untreated) by any of: labs, medications, or ICD-10,  at any time prior to or 6 months after date of index 12 lead ECG (No/Yes)



